// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecpnljfnmpnbxsumorgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjcG5samZubXBuYnhzdW1vcmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODkwOTQsImV4cCI6MjA1ODI2NTA5NH0.-fkLrNRdrx8x_uGtWzmLe8efB7RRz01pHV6Q6XwcJ7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);